# Generated by Django 5.2.7 on 2026-01-08 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_user_phone_cart_cart_custome_ad7f9d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_type', models.CharField(choices=[('drug', 'Drug/Medication'), ('food', 'Food'), ('environmental', 'Environmental'), ('other', 'Other')], default='drug', max_length=20)),
                ('allergen', models.CharField(help_text='Name of allergen (e.g., Penicillin, Peanuts)', max_length=100)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life Threatening')], default='moderate', max_length=20)),
                ('reaction', models.TextField(blank=True, help_text='Description of allergic reaction')),
                ('diagnosed_date', models.DateField(blank=True, null=True)),
                ('diagnosed_by', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Allergies',
                'ordering': ['-severity', 'allergen'],
            },
        ),
        migrations.CreateModel(
            name='ChronicCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(help_text='e.g., Diabetes, Hypertension, Asthma', max_length=100)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('diagnosed_by', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('managed', 'Managed'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'condition_name'],
            },
        ),
        migrations.CreateModel(
            name='CurrentMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(help_text='e.g., 500mg, 10ml', max_length=50)),
                ('frequency', models.CharField(choices=[('once_daily', 'Once Daily'), ('twice_daily', 'Twice Daily'), ('three_daily', 'Three Times Daily'), ('four_daily', 'Four Times Daily'), ('as_needed', 'As Needed'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('other', 'Other')], default='once_daily', max_length=20)),
                ('frequency_notes', models.CharField(blank=True, help_text='Additional frequency info', max_length=100)),
                ('prescribing_doctor', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for taking this medication', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'medication_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow Up'), ('prescription', 'Prescription Note'), ('lab_result', 'Lab Result'), ('general', 'General Note'), ('warning', 'Warning/Alert')], default='general', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False, help_text='Private notes only visible to doctors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_custome_ad7f9d_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_custome_6c3a7f_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_status_762191_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_created_b25042_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_custome_58f6c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='order_items_order_i_26ad88_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='order_items_product_a53db1_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_categor_4083ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_name_6f9890_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_created_a77fb9_idx',
        ),
        migrations.RemoveIndex(
            model_name='productbatch',
            name='product_bat_product_96479e_idx',
        ),
        migrations.RemoveIndex(
            model_name='productbatch',
            name='product_bat_expiry__977560_idx',
        ),
        migrations.RemoveIndex(
            model_name='productbatch',
            name='product_bat_product_27f070_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='questions_custome_395474_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='questions_is_answ_673faa_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='questions_created_fc8d7e_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockrequest',
            name='stock_reque_product_406e6a_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockrequest',
            name='stock_reque_request_c5d595_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockrequest',
            name='stock_reque_status_535a3c_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockrequest',
            name='stock_reque_created_2ad45d_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_usernam_baeb4b_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_email_4b85f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_role_0ace22_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='allergy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chroniccondition',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_conditions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currentmedication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalnote',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalnote',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientmedicalprofile',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
