# Generated by Django 4.2.7 on 2026-01-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_allergy_chroniccondition_currentmedication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active_ingredient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
