# Generated by Django 5.2.7 on 2026-01-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_allergy_chroniccondition_currentmedication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active_ingredient',
            field=models.CharField(blank=True, help_text='Active ingredient(s) in the medication', max_length=200),
        ),
    ]
