# Generated by Django 5.2.7 on 2026-01-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_add_active_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image attachment (e.g., prescription, symptoms)', null=True, upload_to='questions/'),
        ),
    ]
